
# Adapted for this jhudsl repository by Candace Savonen Aug 2021

name: Render and publish Leanpub

# Triggers the workflow on pull requests for the master branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.2

    steps:
      # Checks-out the _Leanpub repository to run the checks
      - name: Checkout code from Leanpub test repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/DaSL_Course_Template_Leanpub
          token: ${{ secrets.GH_PAT }}

      # Copy over the latest leanbuild and use that for the run
      - name: Get latest leanbuild
        uses: |
          sudo apt-get install subversion

          # Make directory for it to land in
          mkdir leanbuild

          # Copy over the latest leanbuild build
          svn export https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/} leanbuild/

      # Run leanpub rendering
      - name: Run leanbuild::bookdown_to_leanpub
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -vanilla .github/render_all.R
