
# Adapted for this jhudsl repository by Candace Savonen Aug 2021

name: Render and publish Leanpub

# Triggers the workflow on pull requests for the master branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    # I have it check out the image that is built from: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/docker/Dockerfile
    container:
      image: jhuds/course_template

    steps:
      # Checks-out the _Leanpub repository to run the checks
      - name: Checkout code from Leanpub test repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/DaSL_Course_Template_Leanpub
          token: ${{ secrets.GH_PAT }}

      # Copy over the latest leanbuild and use that for the run
      - name: Run with latest leanbuild
        uses: |
        # Copy over leanbuild latest
          svn export --force https://github.com/${GITHUB_REPOSITORY}.git/branches/${GITHUB_REF#refs/heads/} leanbuild/

          Rscript -e "devtools::load_all('leanbuild') \
          leanbuild::bookdown_to_leanpub(footer_text = 'check if footer works')"
