
# Adapted for this jhudsl repository by Candace Savonen Aug 2021

name: Update docs

# Triggers the workflow on pull requests for the master branch OR can be manually triggered
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    # I have it check out the image that is built from: https://github.com/jhudsl/ottr_aide_Template/blob/main/docker/Dockerfile
    container:
      image: jhudsl/course_template

    steps:
      # Checks-out the _Leanpub repository to run the checks
      - name: Checkout code from Leanpub test repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/ottr_aide_Quizzes
          token: ${{ secrets.GH_PAT }}

      # Run leanpub rendering
      - name: Run build site
        run: |
          Rscript -e "pkgdown::build_site()"
