
# Adapted for this jhudsl repository by Candace Savonen Aug 2021

name: Update Leanpub Upon Merge

# Triggers the workflow AFTER changes to ottrpal have been merged
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    # I have it check out the image that is built from: https://github.com/jhudsl/OTTR_Template/blob/main/docker/Dockerfile
    container:
      image: jhudsl/course_template

    steps:
      # Checks-out the _Leanpub repository to run the checks
      - name: Checkout code from Leanpub test repo
        uses: actions/checkout@v2
        with:
          repository: jhudsl/OTTR_Quizzes
          token: ${{ secrets.GH_PAT }}

      # Copy over the latest ottrpal and use that for the run
      - name: Get latest ottrpal
        run: |
          sudo apt-get install  -y --no-install-recommends subversion

          # Copy over the latest ottrpal build
          svn export https://github.com/${GITHUB_REPOSITORY}.git/branches/master ottrpal/

      # Run leanpub rendering
      - name: Run ottrpal::bookdown_to_leanpub
        run: |
          Rscript -e "devtools::load_all('ottrpal'); ottrpal::bookdown_to_leanpub(footer_text = '*Please provide any feedback with [this form!](https://forms.gle/hc8Xt3Y2Znjb6M4Y7) We appreciate your thoughts.*')"
          Rscript -e "devtools::load_all('ottrpal'); ottrpal::render_coursera(convert_quizzes = TRUE)"
          rm -r ottrpal


      - name: Create PR with newly rendered docs files
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Show latest ottrpal changes
          signoff: false
          branch: auto_copy_rendered_files
          delete-branch: true
          title: 'GHA: Automated transfer re-render with ottrpal update'
          body: |
            ### Description:
             This PR has changes to this repository's files using the latest ottrpal package changes!
             If they don't look right, file an issue on the ottrpal package: https://github.com/jhudsl/ottrpal/issuesand do not merge.
          labels: |
            automated
          reviewers: $GITHUB_ACTOR

      # Write out PR info
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
